name: ${project.name}
version: ${project.version}
main: com.Ben12345rocks.AdvancedCore.Main
softdepend: [ProtocolLib, Vault]
commands:
  advancedcore:
    description: Plugin command
    aliases: acore
permissions:
  AdvancedCore.Player:
    description: Allows basic access player commands
    default: true
    children:
      AdvancedCore.ValueRequest: true
      AdvancedCore.SelectChoiceReward: true
      AdvancedCore.SetRequestMethod: true
      AdvancedCore.Help: true